output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "tGfHmXgG"
  ssl:
    enabled: true
    ca_trusted_fingerprint: "b9a10bbe64ee9826abeda6546fc988c8bf798b41957c33d05db736716513dc9c"

setup.kibana:
  host: "localhost:5601"
  username: "elastic" <2>
  password: "tGfHmXgG"