/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Avatar: typeof import('./components/Layout/Avatar.vue')['default']
    Banner: typeof import('./components/Layout/UI/Banner/Banner.vue')['default']
    Bar: typeof import('./components/Layout/Bar.vue')['default']
    Button: typeof import('./components/Layout/UI/Button/Button.vue')['default']
    ChannelCard: typeof import('./components/Layout/ChannelCard.vue')['default']
    Drawer: typeof import('./components/Layout/Drawer.vue')['default']
    Form: typeof import('./components/Layout/Login/Form.vue')['default']
    Header: typeof import('./components/Layout/Header.vue')['default']
    HelloWorld: typeof import('./components/Home.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Image: typeof import('./components/Layout/UI/Image/Logo.vue')['default']
    LiveCard: typeof import('./components/Layout/LiveCard.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Logo: typeof import('./components/Layout/UI/Image/Logo.vue')['default']
    Register: typeof import('./components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sheet: typeof import('./components/Layout/UI/Sheet/Sheet.vue')['default']
    Toggle: typeof import('./components/Layout/UI/Toggle/Toggle.vue')['default']
  }
}
