openapi: 3.0.0
info:
  title: Channels Service
  version: 1.0.2
  description: API to manipulate channels data.

paths:
  /channels:
    get:
      summary: Get all channels
      responses:
        "200":
          description: Get all channels successfully
        "500":
          description: Internal Server Error.

  /channels/{id}:
    get:
      summary: Get channel info
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User deleted successfully
        "404":
          description: Not Found.
        "500":
          description: Internal Server Error.

  /channels/create:
    post:
      summary: Create a channel
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                about:
                  type: string

      responses:
        "200":
          description: Created successfully
        "401":
          description: Unauthorized - Invalid Token or Empty Token.
        "400":
          description: BadRequestError - Invalid body.
        "404":
          description: Not Found.
        "500":
          description: Internal Server Error.
  /channels/delete:
    delete:
      summary: Delete a channel
      security:
        - bearerAuth: []

      responses:
        "200":
          description: Deleted successfully
        "401":
          description: Unauthorized - Invalid Token or Empty Token.
        "404":
          description: Not Found.
        "500":
          description: Internal Server Error.
  /channels/:
    put:
      summary: update a channel
      security:
        - bearerAuth: []

      responses:
        "200":
          description: Updated successfully
        "401":
          description: Unauthorized - Invalid Token or Empty Token.
        "404":
          description: Not Found.
        "500":
          description: Internal Server Error.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                about:
                  type: string
                channelId:
                  type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
