name: Build, Test and Deploy Dwitch's Microservices

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm -F auth test

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, user, channels, broadcasts, dwitch-front]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm -F ${{ matrix.service }} build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.service }}
          path: ./packages/${{ matrix.service }}/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform apply -auto-approve
