export const en = {
  message: {
    inLiveTitle: 'Live on Dwitch',
    channelsWouldYouLike: 'Channels maybe you would like',
    channels: {
      toWatchLive: 'Watch live',
      subscribe: 'Subscribe',
      seeMore: 'See more',
      invite: 'Didn`t find anything? Create a channel and invite your friends!',
      createChannel: 'Create Channel',
      startBtn: 'Start Live Streaming',
      inputs: {
        channelName: 'Name',
        description: 'Description',
        confirmBTN: 'Create',
        cancelBTN: 'Cancel',
        errorsMessages: {
          emptyName: 'Name is required.',
          emptyDescription: 'Description is required.',
        },
      },
      feedbacks: {
        dontHaveAChannel: 'You dont have a channel, create one before starting a broadcast!',
        unableToStartTransmission: 'Unable to start transmission',
        broadcastStarted: 'A broadcast has started! Watch the channel',
      },
    },
    login: {
      welcome: 'Welcome',
      email:'E-mail',
      password: 'Password',
      login: 'Sign In',
      notRegistered: 'Not registered yet?',
      register: 'Sign Up',
      errorMessages: {
        default: 'Unable to log in, please check your credentials.',
        emptyEmail: 'E-mail is required.',
        invalidEmail: 'Invalid e-mail.',
        password: 'Password is required',
      },
    },
    register: {
      welcome: 'Welcome',
      email:'E-mail',
      password: 'Password',
      name: 'Name',
      repeatPassword: 'Repeat password',
      signUp: 'Sign Up',
      alreadyRegistered: 'Already Registered?',
      login: 'Sign In',
      errorMessages: {
        default: 'An error occurred while registering.',
        emptyEmail: 'E-mail is required.',
        invalidEmail: 'Invalid e-mail.',
        password: 'Password is required',
        emptyName: 'Name is required.',
        repeatPassword: 'Repeat the password.',
        passwordNotMatch: 'Password does not match.',
      },
    },
  },
}
