export const pt = {
  message: {
    inLiveTitle: 'Ao vivo na Dwitch',
    channelsWouldYouLike: 'Canais que talvez você goste',
    channels: {
      toWatchLive: 'Assistir ao vivo',
      subscribe: 'Inscreva-se',
      seeMore: 'Veja Mais',
      invite: 'Não encontrou nada? Crie um canal e convide seus amigos!',
      createChannel: 'Criar Canal',
      inputs: {
        channelName: 'Nome do Canal',
        description: 'Descrição',
        confirmBTN: 'Criar',
        cancelBTN: 'Cancelar',
        errorsMessages: {
          emptyName: 'Informe um nome.',
          emptyDescription: 'Informe uma descrição.',
        },
      },
    },
    login: {
      welcome: 'Bem-vindo',
      email:'E-mail',
      password: 'Senha',
      login: 'Entrar',
      notRegistered: 'Ainda não é cadastrado?',
      register: 'Cadastre-se',
      errorMessages: {
        default: 'Não foi possível realizar o login, verifique suas credenciais',
        emptyEmail: 'Informe um e-mail',
        invalidEmail: 'Informe um e-mail válido.',
        password: 'Informe uma senha',
      },
    },
    register: {
      welcome: 'Bem-vindo',
      email:'E-mail',
      password: 'Senha',
      name: 'Name',
      repeatPassword: 'Repetir senha',
      signUp: 'Cadastrar-se',
      alreadyRegistered: 'Já é cadastrado?',
      register: 'Faça o login',
      errorMessages: {
        default: 'Ocorreu um erro ao fazer o cadastro.',
        emptyEmail: 'Informe um e-mail',
        invalidEmail: 'Informe um e-mail válido.',
        password: 'Informe uma senha',
        emptyName: 'Informe um nome',
        repeatPassword: 'Repita a senha',
        passwordNotMatch: 'As senhas devem ser iguais.',
      },
    },
  },
}
